### ISSUE TITLE
1337-matching fails on passwords with different letters for same subsitution

### ISSUE THREAD

**Issue by kabarakh** [dropbox/zxcvbn#101]
We wanted to use zxcvbn with own dictionaries and additional checks.

One of those checks is to check the password against the name of the user. When a user named egeling uses the password 3ge11ng zxcvbn doesn't find the match with the username but finds brute force (3), regex (ge), repeat (11) and regex (ng) which is considered as save.

What we found is that with the regex substitution the passwords egellng and egeiing are validated against the dictionary, but never egeling (which would be found).

**Comment by lowe** [comment]
Hi @kabarakh, that's right, l33t matching currently only allows one sub -> letter mapping. I'd worry about a combinatorial explosion of matching if we try every permutation of every possible substitution, eg: 

egeling
egellng
egeilng
egeiing
