### ISSUE TITLE
consider incorporating Monte Carlo strength evaluation

### ISSUE THREAD

**Issue by roycewilliams** [dropbox/zxcvbn#102]
Based on academic work published here (free access):

http://www.eurecom.fr/en/publication/4711/detail/monte-carlo-strength-evaluation-fast-and-reliable-password-checking

Quoting:

> The proposed method requires little resources, applies to a wide set of probabilistic models, and is characterised by highly desirable convergence properties. The experiments demonstrate the scalability and generality of the proposal. In particular, the experimental analysis reports evaluations on a wide range of password strengths, and of state-of-the-art attacks on very large datasets, including attacks that would have been prohibitively expensive to handle with existing simulation-based approaches.

**Comment by lowe** [comment]
Hi @roycewilliams, that's a great paper. I'm not sure how to incorporate Monte Carlo sampling into zxcvbn, so I'm going to close this issue for now. What I understand so far: 
 
* the method they propose takes a probability from a generative guessing model (PCFG, Markov, etc) and converts it into a guess order. That conversion from probability -> guesses is time- and space-efficient. 

* however, those underlying probability models typically require quite a bit of space, orders of magnitude more than will fit into a small client library like zxcvbn. I think there's some remaining work to build small, portable probability models that have nice approximations to the larger ones. If you know of a way to incorporate Monte Carlo sampling that doesn't require the support of a backing server, let me know!

**Comment by roycewilliams** [comment]
Hi, @lowe - thanks for the thoughtful analysis. I hadn't done enough analysis of my own, and didn't recognize the space requirement. And approximation may indeed be possible someday, but beyond my ken at present. :) But I'll keep an eye out!
