### ISSUE TITLE
Inputting an empty string returns a score of 4

### ISSUE THREAD

**Issue by elwayman02** [dropbox/zxcvbn#104]
![developer_tools_-_http___localhost_4200_](https://cloud.githubusercontent.com/assets/1325482/10744954/fb0129ae-7bfa-11e5-8e5c-3ebda7007896.png)

**Comment by lowe** [comment]
this is a regression following v4 -- thanks for reporting!

**Comment by elwayman02** [comment]
No problem, thanks for fixing it! :)
