### ISSUE TITLE
Example on the web

### ISSUE THREAD

**Issue by hickford** [dropbox/zxcvbn#107]
Is there an example on the web? Perhaps similar to https://howsecureismypassword.net/ ? Would you add it to the readme?

**Comment by hickford** [comment]
I'd like to link my friends to https://howsecureismypassword.net/ but I'm not convinced the results are reliable

For example given the password `Potatoes01` that website says

> It would take a desktop PC about 6 years to crack your password

Whereas your app suggests

> offline_fast_hashing_1e10_per_second: 'less than a second'

I think that's more believable. 81A2A395943F1FF3F5E80BFC5E7F5313

**Comment by hickford** [comment]
I found https://dl.dropboxusercontent.com/u/209/zxcvbn/test/index.html

Has anyone made a more user-friendly site?

**Comment by lowe** [comment]
Hi @hickford, that interactive demo is the only one I've made. Its goal is to directly show the return value of the library, hence the bare-bones feel. 

In terms of user-friendliness, I'd recommend directly trying zxcvbn on sites that use it (some of these are using older versions of the lib): [dropbox.com/register](http://dropbox.com/register), [dashboard.stripe.com/register](https://dashboard.stripe.com/register) and [coinbase.com/signup](https://www.coinbase.com/signup) are three examples, but there's many others.

**Comment by hickford** [comment]
Hi Dan. Thanks for your reply. Cool I might try my hand at making a https://howsecureismypassword.net/ style site

**Comment by hickford** [comment]
Thanks for your help. https://how-strong-is-my-password.divshot.io/
