### ISSUE TITLE
Suggestion: memorability score

### ISSUE THREAD

**Issue by qgustavor** [dropbox/zxcvbn#111]
I think zxcvbn could analyze the probability of the password being remembered or not. To explain how it can be used I will show some examples:

    password: nevergonnagiveyouup
    score = 4; guesses_log10 = 16; memorability: 90%
    warning: this password seems easy to remember: it's recommended to
    use random unrelated words in a way not found in literature or music.

    password: KRA13n1AQf8ggI0T
    score = 4; guesses_log10 = 16; memorability: 0%
    warning: this password seems hard to remember: it's recommended to
    not write it in insecure places, like post-its and plain text files.

**Comment by ebeeson** [comment]
Do you have a proposed metric for determining memorability?

Also, I disagree with your statement discouraging writing it down. Discouraging people from saving passwords somewhere is how we've ended up with so many terrible passwords in the world. Writing passwords in a journal is basically on offline password manager, which is probably actually more secure (and less complicated to use).

**Comment by qgustavor** [comment]
Sorry for the bad idea but I meant insecure ways like in post-its or plain
text files. I have saw many cases like this.
The warnings are just examples, if some is wrong but can be corrected fell
free to fix it. Why about "your password seens secure and hard to remember:
if you're storing it somewhere do it safety"
2015/11/05 17:38 "Erik Beeson" <notifications@github.com>:

**Comment by qgustavor** [comment]
Currently I'm calculating  the sum of `guesses_log10` for non `bruteforce` patterns then dividing for the result `guesses_log10`. Maybe someone know some way to improve this.

**Comment by lowe** [comment]
Hi @qgustavor, thanks for the suggestion but I'm going to avoid adding a memorability metric for now, mainly because I don't know how to measure it, or necessarily what advice to give as a result.
