### ISSUE TITLE
3 Years ?

### ISSUE THREAD

**Issue by tommyent** [dropbox/zxcvbn#117]
![screen shot 2015-11-21 at 11 06 22 pm](https://cloud.githubusercontent.com/assets/509970/11322033/3c4fcb86-90a5-11e5-80a9-ef6fbc083200.png)

**Comment by MacGyverNL** [comment]
Looks related to #122, see commit d20704b

**Comment by lowe** [comment]
Yup, #122 has details on why bruteforce matching is now this conservative. 
One fix is better "random string" detection.
