### ISSUE TITLE
entropy property removed?

### ISSUE THREAD

**Issue by esoul128** [dropbox/zxcvbn#119]
I was trying to use this code with another product that wanted to use the entropy property of the resulting object, but it is returning undefined.  Has this property been removed?

**Comment by esoul128** [comment]
Nevermind, found the removal of this in the release log.  Sorry to waste a post.

**Comment by varac** [comment]
For the record, [this is the commit that removes the entropy key](https://github.com/dropbox/zxcvbn/commit/a1be663b7533f990d094ae9a4f76ae51491ee0f4)
