### ISSUE TITLE
Score descriptions

### ISSUE THREAD

**Issue by ebeeson** [dropbox/zxcvbn#120]
Is there any official vernacular for mapping `score` to English? Something like:

```
0 terrible
1 very poor
2 weak
3 mediocre
4 good
5 excellent
```

Or:

```
0 worst
1 worse 
2 bad
3 good
4 better
5 best
```

Or:

```
0 awful
1 poor
2 mediocre
3 okay
4 decent
5 excellent
```

Any suggestions?

**Comment by MeTaNoV** [comment]
When I use in in my Polymer Element, I default to:
0 very weak
1 weak
2 medium
3 strong
4 very strong
Note that value 5 does not exist! :)

**Comment by ebeeson** [comment]
Thanks for the heads-up. You're right about 0-4. I was confused by the [release notes](https://github.com/dropbox/zxcvbn/releases/tag/4.0.1) that say "`score` is still on a 0-5 scale".
