### ISSUE TITLE
Caesar cipher not recognized

### ISSUE THREAD

**Issue by XelNika** [dropbox/zxcvbn#121]
Using a caesar shift results in very good scores for otherwise common passwords.
Shifting Password by just one to Qbttxpse results in a good score.

I don't know if this is commonly used or how checking for it would affect execution time, but perhaps it's worth adding.

**Comment by lowe** [comment]
Hi XelNika, 

It's been suggested in the past:

https://github.com/dropbox/zxcvbn/pull/75

But I'm not aware of caesar ciphers being a commonly used password pattern, and including them comes at a considerable runtime cost (~26x more dictionary matching time) 

Thanks anyhow for suggesting!
