### ISSUE TITLE
Bruteforce cardinality of 10 requires explanation in the output

### ISSUE THREAD

**Issue by MacGyverNL** [dropbox/zxcvbn#122]
From dropbox/zxcvbn@d20704b I understand that bruteforce time estimation is a hard problem, and there's insufficient research to have an actual fair estimation. However, I think this estimate is far too conservative for passwords that have both been found to be "bruteforcable at best" *and* known to be randomly generated.

It is good to be conservative, however, as demonstrated in the discussion at <https://github.com/bwesterb/pol/issues/11>, and subsequent discussion on IRC, when zxcvbn gives an estimate of "4 months" for a randomly generated, bruteforcable at best, password with ~47 bits of entropy, people get confused. I think a warning about the uncertain nature of zxcvbn's current bruteforce estimation might be warranted, along the lines that if a password actually comes from an RNG the estimate is likely too conservative.

**Comment by lowe** [comment]
Hi @MacGyverNL, 

zxcvbn makes no assumption about whether passwords are randomly generated. If you know a password is random, I'd suggest evaluating it as something like expected guesses = .5 * C^L for an alphabet size of C and length of L.

The old version of zxcvbn used a similar calculation for unmatched "bruteforce" regions. However, by far the common case for a typical deployment is that unmatched regions correspond to words that aren't in the dictionary, or other patterns that the library can't identify. The move to 10^L across the board is an attempt to make the new version more conservative on areas that it can't match, to avoid overestimation.
