### ISSUE TITLE
zxcvbn for Java.

### ISSUE THREAD

**Issue by vvatanabe** [dropbox/zxcvbn#123]
Hi all.
Sorry, this isn't the issue. I might want to inform.
I've port zxcvbn to Java. Please look at the following.

[zxcvbn4j](https://github.com/nulab/zxcvbn4j)

zxcvbn of the algorithm is really nice. It became very study.
I want to build a good relationship with you.

For bugs, questions and discussions please use the [Github Issues](https://github.com/nulab/zxcvbn4j/issues).

Thanks.

**Comment by lowe** [comment]
This is great! Thanks for sending along. I just updated the [README](https://github.com/dropbox/zxcvbn) to include a list of ports. Take care :D
