### ISSUE TITLE
Easy Password is scored higher in version 4.2.0 than in version 1.1.0 

### ISSUE THREAD

**Issue by thegame8714** [dropbox/zxcvbn#131]
Hi All,

I'm implementing your library in my webapp but I had different score result in the frontend and in the backend (using this PHP porting https://github.com/bjeavons/zxcvbn-php) .

I've checked their versioning and looks like that they are using the same algorithm using by you in the version 1.1.0. 

The funny thing is that the password "aaasssd" has a score of 2 in the version 4.2.0 while it has a score of 0 in the version 1.1.0. 

Am I missing something? I don't understand how such an easy password can be considered "weak" (I think this is correct) in an earlier version and "medium" in the latest version. 

What am I missing?

Thank you for your answer

Regards

Fabio

**Comment by DKhalil** [comment]
The last version to seem to have a correct scoring is 3.5.0

I'm going to look further into this and see if I can find the bug

**Comment by lowe** [comment]
I'm unable to repro in the latest zxcvbn release (4.2.0). I get a score of 1. 

```
> zxcvbn('aaasssd')
{ password: 'aaasssd',
  guesses: 119934,
  guesses_log10: 5.078942318371442,
  sequence:
   [ { pattern: 'dictionary',
       i: 0,
       j: 5,
       token: 'aaasss',
       matched_word: 'aaasss',
       rank: 4997,
       dictionary_name: 'passwords',
       reversed: false,
       l33t: false,
       base_guesses: 4997,
       uppercase_variations: 1,
       l33t_variations: 1,
       guesses: 4997,
       guesses_log10: 3.698709349442587 },
     { pattern: 'bruteforce',
       token: 'd',
       i: 6,
       j: 6,
       guesses: 11,
       guesses_log10: 1.041392685158225 } ],
  calc_time: 6,
  crack_times_seconds:
   { online_throttling_100_per_hour: 4317624,
     online_no_throttling_10_per_second: 1199.34,
     offline_slow_hashing_1e4_per_second: 11.9934,
     offline_fast_hashing_1e10_per_second: 0.0000119934 },
  crack_times_display:
   { online_throttling_100_per_hour: '2 months',
     online_no_throttling_10_per_second: '20 minutes',
     offline_slow_hashing_1e4_per_second: '12 seconds',
     offline_fast_hashing_1e10_per_second: 'less than a second' },
  score: 1,
  feedback:
   { warning: 'This is similar to a commonly used password',
     suggestions: [ 'Add another word or two. Uncommon words are better.' ] } }
```

I'm not sure that the zxcvbn-php port is using the same data and algorithm. I've made steady improvements to the js version over the last several months.

One option you might want to consider is avoiding server-side zxcvbn calls. You can use the client to do light policy enforcement (for example, only allow passwords requiring 500 or more guesses, 1000 or more guesses) but not be strict about it, having a simple length-6 minimum password requirement (or no requirement) on the server.

**Comment by DKhalil** [comment]
This password on the other hand gets a score of 3: apple!!11

As I wrote you in the e-mail: adding !!11 is an autoscore of 3 with any password.

As is the combination of any 2 special chars combo like '??!!', '@@..',

Or 'power&power'

**Comment by lowe** [comment]
Hi @DKhalil,

You can see a visualization here for how those passwords are being rated: 
https://dl.dropboxusercontent.com/u/209/zxcvbn/test/index.html

apple!!11 is matched as word-repeat-repeat, which seems right to me.

**Comment by DKhalil** [comment]
Yeah, but is it actually a good password? Is 'pass.word.' a good password worth 3 points? Is 'zxcvbn.qwerty' a good password?

**Comment by lowe** [comment]
zxcvbn isn't currently able to catch words with non-substituting characters interspersed, so, I would say that's the problem, vs the scoring scale. 

any model has limitations. i'd be curious to see roughly what order of magnitude of guesses a cracking lib like hashcat or john the ripper guesses 'pass.word.'. that would help inform future work on these cases.
