### ISSUE TITLE
Check for exports first.

### ISSUE THREAD

**Issue by nickpoorman** [dropbox/zxcvbn#14]
It would be nice if the zxcvbn function was an export which doesn't happen if window is available. I think exports should be checked before window so we don't pollute the global namespace.

Currently it is:

```"undefined" !== typeof window && null !== window ? (window.zxcvbn = o, "function" === typeof window.zxcvbn_load_hook && window.zxcvbn_load_hook()) : "undefined" !== typeof exports && null !== exports && (exports.zxcvbn = o)```

**Comment by benmosher** [comment]
:+1:

FWIW, I am using

```js
var zxcvbn = require('zxcvbn') || window.zxcvbn;
```

to hack around this in a Webpack'd CommonJS frontend module. Seems to work in Node too.

**Comment by mathieumg** [comment]
Using the exports-loader:

```javascript
var zxcvbn = require("exports?zxcvbn!zxcvbn");
```

**Comment by benmosher** [comment]
Would that work with the current master revision? 

The `index.js` specified in `package.json` is already exporting the function from `zxcvbn.js`, but when the module is executed in the browser at runtime, it assigns to a global instead. Though I can't find current documentation about the `exports` loader. Does it handle this?

I would think it would at least need to be `exports?zxcvbn!zxcvbn/zxcvbn`. I can't see where there is a `zxcvbn` defined, though.

**Comment by benmosher** [comment]
Also, it would probably be better served as a fix in the module proper (as OP suggests), as I would think the `require`-er should not need to consider the ultimate execution environment.

**Comment by lowe** [comment]
Thanks for bringing this up. I followed this UMD in case you're curious:  
https://github.com/umdjs/umd/blob/master/commonjsStrict.js

**Comment by binarykitchen** [comment]
still doesn't work when packed with webpack. returns `undefined`.
