### ISSUE TITLE
error in Internet Explorer 8 using zxcvbn/js

### ISSUE THREAD

**Issue by EISLtd** [dropbox/zxcvbn#141]
I'm getting this error using zxcvbn.js when doing 'var result = zxcvbn(password);'

----
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; .NET4.0E)
Timestamp: Sun, 27 Mar 2016 13:48:44 UTC

Message: Object doesn't support this property or method
Line: 18
Char: 4365
Code: 0
URI: http://.../zxcvbn.js
-----

**Comment by lowe** [comment]
Hi @EISLtd, we no longer support IE8, but IE9 and above should work. You can see our supported platforms here: [saucelabs browser status](https://saucelabs.com/u/dropbox-zxcvbn).
