### ISSUE TITLE
Source map in dist is broken

### ISSUE THREAD

**Issue by binarykitchen** [dropbox/zxcvbn#148]
Chrome says

```
Failed to parse SourceMap: http://localhost:xxx/yyy/zxcvbn.js.map
```

Probably because of those absolute directories which look bad
```
  "sources": [
    "node_modules/browserify/node_modules/browser-pack/_prelude.js",
    "/Users/dan/zxcvbn/src/adjacency_graphs.coffee",
    "/Users/dan/zxcvbn/src/feedback.coffee",
    "/Users/dan/zxcvbn/src/frequency_lists.coffee",
    "/Users/dan/zxcvbn/src/main.coffee",
    "/Users/dan/zxcvbn/src/matching.coffee",
    "/Users/dan/zxcvbn/src/scoring.coffee",
    "/Users/dan/zxcvbn/src/time_estimates.coffee"
  ],
```

**Comment by volgin** [comment]
Any plans to resolve this?

**Comment by lowe** [comment]
thanks for the reminder and sorry for the delay -- I didn't realize [exorcist](https://www.npmjs.com/package/exorcist) used absolute paths by default, and of course it worked on my machine, so I didn't notice :) 

fixed by adding the --base option to exorcist.

**Comment by binarykitchen** [comment]
@lowe thanks for that but can you publish v4.4.0? its zip is not in the archive, see https://github.com/dropbox/zxcvbn/releases

thanks

**Comment by lowe** [comment]
Whoops, fixed, thanks for catching.

**Comment by binarykitchen** [comment]
@lowe good boy :)

**Comment by binarykitchen** [comment]
but i discovered another small bug just now: it has the `v` prefix. all other versions don't.
