### ISSUE TITLE
How to run zxcvbn?

### ISSUE THREAD

**Issue by richardk2016** [dropbox/zxcvbn#150]
What must be don to run zxcvbn on my webspace? I uploaded the project to my webspace provider and opened the URL I choose. http://my.web.space/zxcvbn/demo/index.html

I can't see any examples and nothing happens when I type into the box. In the readme I saw something like "bower install zxcvbn". I don't have any command shell with my webspace. I can up- or download things with SFTP or run HTML Pages with my browser. Not more not less. Javascript works fine. I run wordpress on that webspace.

Sorry for that maybe silly question but I am not a webdeveloper. 

What must I do to run the demo?

**Comment by lowe** [comment]
Hi @richardk2016, try downloading [zxcvbn.js](https://raw.githubusercontent.com/dropbox/zxcvbn/master/dist/zxcvbn.js) directly and adding this to your `.html`

```
<script type="text/javascript" src="path/to/zxcvbn.js">
</script>
``` 

Then you'll be able to run it after your page loads. For example, from Chrome, go to `View > Developer > JavaScript Console`, find the command prompt, and type `zxcvbn('helloworld')`.

Good luck!
