### ISSUE TITLE
Should remove Meteor package instruction from README

### ISSUE THREAD

**Issue by yyl** [dropbox/zxcvbn#152]
So maybe we should remove its install instruction from the README? Because that package is not working under Meteor 1.3 anymore.

I just installed and tried [codetheweb:zxcvbn](https://atmospherejs.com/codetheweb/zxcvbn) in Meteor 1.3 but it says `ReferenceError: Can't find variable: zxcvbn`.

I think @codetheweb also mentioned in a closed issue that package is not maintained: https://github.com/codetheweb/zxcvbn/issues/1

**Comment by codetheweb** [comment]
^ Correct.  I haven't had much time to update it; and now Meteor supports installing from NPM packages, making my 'port' obsolete.  Probably best if the reference in the README to my package is just removed.

**Comment by codetheweb** [comment]
#153

**Comment by lowe** [comment]
Thanks!
