### ISSUE TITLE
Customize threshold for scores

### ISSUE THREAD

**Issue by SirCmpwn** [dropbox/zxcvbn#162]
I think it'd be nice to be able to customize the guesses threshold for the assigned score based on your hashing algorithms. I'm using an 1e10 algorithm (for passwords destined for /etc/shadow) and "less than a second" passwords can get a score of 4.

**Comment by evilaliv3** [comment]
This is a nice desiderata higly required for whatever use case.

While the general idea zxcvbn is perfect the thresholds will be obviously subject to the pass of time.

It would be important so that this thresholds could be configurable in order to raise them as the time inesorable passes by.

**Comment by evilaliv3** [comment]
@SirCmpwn temporarly what you you can do is use the value ```guesses_log10``` and design an external function like the following:

```javascript
function customScore(zxcvbn_result, thresholds) {
    for(var i=0; i<thresholds.length; i++) {
        if(zxcvb_result.guesses_log10) < thresholds[i]) {
          return i;
        } 
    }

    return thresholds.length + 1;
}

yourScore = customScore(zxcvbn_result, [1, 2, 16, 30]);
```

this will give you 0, 1, 2, 3 ,4 withc thresholds 10^1, 10^2, 10^16, 10^30

**Comment by lowe** [comment]
Hi all, 

The scoring is just a suggestion, and based on an online guessing threat, so it won't work for everyone (certainly not most offline scenarios). 

For this sort of use case, I suggest using only the `guesses` or `guesses_log10` property and implementing your own short [`guesses_to_score`](https://github.com/dropbox/zxcvbn/blob/master/src/time_estimates.coffee#L18) function. 

Similarly, some adopters won't want a 5-point score -- maybe they'll want to fill a strength bar continuously from 0 to 100.
