### ISSUE TITLE
Another "port"

### ISSUE THREAD

**Issue by Tostino** [dropbox/zxcvbn#179]
Hey there, I just got around to cleaning up and open sourcing a library I built for my company which implements most of the methods that zxcvbn uses, as well as some custom.

We needed a Java library that did the same type of work that zxcvbn does, and back in 2014 when I started looking around, I didn't see anything that was in good condition, so I started one from scratch (I know there are some now...).  We've been using it internally for a good while, but I didn't get around to cleaning up, and commenting the code until a few days ago. 

I wanted to focus on being highly configurable for different use-cases, and I think I achieved that pretty well, though any feedback is more than welcome.

It can be found here: [nbvcxz](https://github.com/GoSimpleLLC/nbvcxz)

Mind putting a link under the "ports" section?

**Comment by lowe** [comment]
Merged your PR. Thanks again for porting.
