### ISSUE TITLE
Consistent release tagging

### ISSUE THREAD

**Issue by binarykitchen** [dropbox/zxcvbn#186]
Initially reported in https://github.com/dropbox/zxcvbn/issues/148#issuecomment-249992432 I think I better move this issue in its own ticket:

In your releases at https://github.com/dropbox/zxcvbn/releases I can see that you sometimes prefix released versions with `v` then some aren't.

This can be dangerous. Let me explain. A PR of mine for a zxcvbn package in ClojureScript has been accepted and is fetching the zxcvbn source code from this url

```
(str "https://github.com/dropbox/zxcvbn/archive/v" +lib-version+ ".zip")
```

See https://github.com/cljsjs/packages/blob/0c9fd5573b91ba54507015ac3bcb6c075c487d39/zxcvbn/build.boot#L22

Now, as you can imagine, that cljsjs package wont become installable when you remove the `v` prefix for existing releases and/or future releases.

Let me know your thoughts. Ultimately I just want to know if the `v` stays or not.

**Comment by lowe** [comment]
Hi @binarykitchen,

I'll use the `v` from now on. 

This was originally a mistake from using the `npm version` command, which I didn't realize adds the `v`. Once I had pushed it out, it was too late, as I didn't want to modify the shared github repo. 

From poking around, it looks like it is best practice to keep the `v`, as it is the more common convention among npm packages. I'll keep it consistent moving forward.
