### ISSUE TITLE
Ability to turn down the plugin's harshness of grading?

### ISSUE THREAD

**Issue by gregblass** [dropbox/zxcvbn#187]
I've given a bunch of demos of my product now using zxcvbn, and every time they're getting 0's or very low scores on the password meter.

I'm implementing zxcvbn for another client project right now, and I wanted to reach out to see if its possible to lower the strictness of requirements?

These clients are small time right now and don't need military grade password standards - just something to make sure it isn't completely horrible.

So ideally I'd like to pass in an option to tone down the requirement level a bit so it doesn't grade so harshly.

Is this possible?

**Comment by gregblass** [comment]
This is actually not really the job of zxcvbn, its the job of its wrapper.

**Comment by shssoichiro** [comment]
I would argue that if they're getting 0 on the password meter, then zxcvbn is doing its job by stopping them from having an easily guessable password.

You can adjust the minimum score that you allow in your application, but I would highly recommend against allowing a score of 0 or 1.
