### ISSUE TITLE
Demo doesn't work.

### ISSUE THREAD

**Issue by aviogit** [dropbox/zxcvbn#188]
I'm totally newbie about javascript, css and html, but cloning from master, I think that the demo is not working properly. Placing zxcvbn dir in my www directory, and pointing my browser to http://myserver/zxcvbn/demo/index.html shows two working links to Dropbox introduction and github code, an input field that when filled doesn't do nothing and an empty "Examples" section.

I tried to add:

<script type="text/javascript" src="../dist/zxcvbn.js"></script>

to actually load the javascript (no signs of zxcvbn-async.js in the whole repo) and call:

<script>document.write("hello world");zxcvbn("password1");document.write("password1: " + result.entropy);</script>

in the middle of the examples div, with no luck.

This is the console stack trace I get:

require.js:1915 GET http://myserver/zxcvbn/demo/demo.js req.load @ require.js:1915context.load @ require.js:1659Module.load @ require.js:828Module.fetch @ require.js:818Module.check @ require.js:848Module.enable @ require.js:1161context.enable @ require.js:1531(anonymous function) @ require.js:1146(anonymous function) @ require.js:132each @ require.js:57Module.enable @ require.js:1098Module.init @ require.js:782(anonymous function) @ require.js:1435
require.js:166 Uncaught Error: Script error for: demo
http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:166context.onScriptError @ require.js:1701
index.html:55 Uncaught ReferenceError: zxcvbn is not defined(anonymous function) @ index.html:55

Could someone please fix the demo and make it a little bit more dummy-proof to help people like me to get started?

Thanks and cheers
Avio

**Comment by aviogit** [comment]
Ok, coffee files need to be converted to javascript.

#> sudo apt install coffeescript

and 

#> coffee -c demo.coffee

solved the problem (on Ubuntu 14.04 x86_64).

**Comment by worc** [comment]
should probably add that to the readme or package.json
