### ISSUE TITLE
Webpack discouragement in readme

### ISSUE THREAD

**Issue by karolmie1** [dropbox/zxcvbn#193]
Why webpack would be discouraged as a bundling tool?
zxcvbn can be simply put into separate bundle and loaded on demand.
That's the magic of webpack :)

**Comment by lowe** [comment]
Hi @karolmie1, definitely, but the question is -- bundled with what? 

The README only aims to discourage bundling it with site-wide JS that gets loaded everywhere. If you do already have a separate bundle for pages that contain password flows, by all means, webpack is a great choice.
