### ISSUE TITLE
Main location invalid in package.json

### ISSUE THREAD

**Issue by KyleNeedham** [dropbox/zxcvbn#197]
Package.json has an incorrect location for the main file.

`"main": "lib/main.js",`

I assume the correct location is `dist/zxcvbn.js`?

**Comment by punkstarkat** [comment]
"main": "lib/main.js",
dist/zxcvbn.js

**Comment by KyleNeedham** [comment]
This issue doesn't appear to have been resolved, so what's the reason for closing?
