### ISSUE TITLE
"try zxcvbn interactively" link in README is broken

### ISSUE THREAD

**Issue by ColinNiu** [dropbox/zxcvbn#210]
The "try zxcvbn internatively" link in README, Usage section is broken now.
https://dl.dropboxusercontent.com/u/209/zxcvbn/test/index.html seems returned a 404.

I think this demo is useful and helps people understand zxcvbn more easier.

**Comment by 7776** [comment]
Dropbox removed public folder sharing on Sep 1st, this would need to be hosted elsewhere.

**Comment by georgy7** [comment]
GitHub Pages may be suitable.

**Comment by TaviRider** [comment]
The project includes a demo section which looks like the source behind the "try zxcvbn interactively" link. I wonder if this is the same code because I can't get it to function. It doesn't work locally because of script references, and serving it up through a simple web browser like python's SimpleHTTPServer gives various errors related to line 9 of index.html.

**Comment by qaisjp** [comment]
=(

**Comment by TaviRider** [comment]
The original tech demo is still available from [archive.org](http://web.archive.org/web/20170829001755/https://dl.dropboxusercontent.com/u/209/zxcvbn/test/index.html).

**Comment by lowe** [comment]
Hi all -- this is now fixed via GitHub pages. Sorry for the delay: I used to host this via Dropbox's old `Public/` directory feature, which was discontinued years ago. (It continued to work for me as a legacy user up until around September.) 

Separately, I'm in touch w/ Dropbox about fixing the broken demo link in the tech blog post.

**Comment by cam8001** [comment]
Damn, missed by 2 minutes :)

The stuff around the errors was to do with compiling of demo.coffee to demo.js, plus some pathing issues. I published the demo via gh-pages here too: http://zxcvbn.camerontod.com/

Thanks for your help lowe!

**Comment by lowe** [comment]
Thanks anyway @cam8001, very kind of you!
