### ISSUE TITLE
Enhance documentation: list all the check types

### ISSUE THREAD

**Issue by paulbarker** [dropbox/zxcvbn#219]
I'd like to use this amazing library in a project but my stakeholders are asking if it supports their requirements. For example, they've given me this list:

- Contains a minimum of 8 characters
- Contains three of the following four character categories 
  - English upper case characters (A-Z) 
  - English lower case characters (a-z) 
  - Base 10 digits (0-9) 
  - Non-alphanumeric characters (eg !@#$%^&*()_+|~- =\`{}[]:";'<>?,./) 
- Are not a word in any language, slang, dialect, jargon, etc. 
- Are not based on personal information, name, user name, company etc. 

Many apologies if I've missed it in the documentation but I can't see anywhere a simple list that details all the types of checks that zxcvbn covers (like that list above) so it's really difficult to compare with other libraries (mind you, I can't find much documentation for them either...) and impossible to assess whether it meets requirements or not.

**Comment by Tostino** [comment]
I know this is a very late response, but I thought i'd leave one regardless.

The whole point of zxcvbn is to not require those types of arbitrary checks, but to give a best-guess on how many tries on average it would take to crack based on all of the matching types it implements.

Each of those matching types give a score for their part of the password independently, and it's all added up (as i'm sure you understand).

Those types of arbitrary rules are the exact opposite of what zxcvbn helps enforce. Those rules are a round about attempt at making people pick a good password, which are easily worked around. For example, P@ssw0rd! meets all your criteria with flying colors. Is it a good/secure password though?

**Comment by paulbarker** [comment]
Yes that all makes sense. I'd kind of come to the same conclusion but this was a (crazy) client requirement. We actually implemented the additional checks over the top and then wrapped them as an option. We don't see the point or the need for it so most users will leave it un-checked and we're using the library as it was intended (which works very nicely indeed, many thanks)!
