### ISSUE TITLE
Have I Been Pwned API Support

### ISSUE THREAD

**Issue by leifdreizler** [dropbox/zxcvbn#236]
**Feature Request**
An optional flag for running a given password against the [HIBP API](https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange). Presence of the password in the HIBP database would result in a lowered score and a custom message. To save on requests to the HIBP API it could run after the basic checks have completed—no need to run "password1!" against HIBP. Requests to the API could fail silently.

**Comment by mkopinsky** [comment]
A wrapper library which calls zxcvbn and then HIBP would make more sense than integrating the two directly (imo). I'd venture that *someone* out there must have built such a thing (whether as a library or just in their application code) - anyone want to open source it (and link from this issue)?

**Comment by 1013arleen** [comment]
Guess who knows all your code stacktraces and stashes? Me. The girl you hacked. 
BadFood Sucks.
Cheers criminal!

**Comment by robalb** [comment]
In my react web app i use a function that does exactly that: it calls `zxcvbn` and returns the usual object, but if the security score is greater than 2 the password is also checked agains HIBP using the k-anonymity apis, and the result is adjusted.

It's definelty not clean code, but if anyone is interested the code is [here](https://github.com/robalb/studentsplanner/blob/master/pinboards.it/src/utils/lpse.js)

**Comment by mchubby** [comment]
Edit: oops, I thought I was in the KeepasXC repo, sorry if this comes out as off-topic

Janek Bevendorff **@phoe​rious** addressed this:
https://keepassxc.org/blog/2018-02-24-pwned-database/

On Keepass I use the (open-source) [HIBPOfflineCheck plugin](https://github.com/mihaifm/HIBPOfflineCheck) that tries to match the SHA1 against a downloaded database dump at https://haveibeenpwned.com/Passwords

It has the benefit of not supplying the hash to an external API but eats quite a lot of space (22+ GiB).

**Comment by robalb** [comment]
> Janek Bevendorff **@phoe​rious** addressed this:
> https://keepassxc.org/blog/2018-02-24-pwned-database/

Off topic disagreement: HIBP integration is useless only if you are building a password manager.
As the article points out HIBP is not very effective for measuring password strength, but combined with zxcvbn in a login form It can detect reused passwords, or common passwords that are not in the zxcvbn list. It's pretty useful

**Comment by oscrx** [comment]
If anyone is going to create a wrapper, this might be a useful reference implementation:  https://github.com/jamiebuilds/havetheybeenpwned/blob/master/lib/implementation.js
