### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by SimonSchick** [dropbox/zxcvbn#242]
Is this project still being maintained? Last commit was 2 years ago, issues and PRs don't seem to be answered.

**Comment by xtrasimplicity** [comment]
@lowe, Are you able to shed some light on this? I'm sure there's a few people out there who would be keen on helping out, if it is in-fact no longer maintained. :)

**Comment by lowe** [comment]
Hi folks -- zxcvbn is still maintained but in short, infrequent bursts. a major revamp is in the works that will remove the coffeescript dependency along with some of the other bigger criticisms currently listed on /issues. 

2 years is understandably a long time, but I'm also not aware of any blockers / critical bugs. Please post if so and we'll take a look.

**Comment by SimonSchick** [comment]
@lowe thanks for clarifying!

**Comment by arregit** [comment]
@lowe - Your comment should be kindly put at the top of readme.md

**Comment by worc** [comment]
in the mean time, is there any effort being put into reviewing issues/PRs? it seems like a lot of them are trivial (either easy to close or merge).
