### ISSUE TITLE
No more dogfooding?

### ISSUE THREAD

**Issue by stephenreay** [dropbox/zxcvbn#254]
We've implemented this library for user password strength checks, and (after resolving some different language implementation bugs) I believe it's truly useful - the problem is of course users want to suggest they know better.

It's no longer possible to say  "well this library is from Dropbox, who use it for their site" - because there is apparently no password strength testing on the Dropbox site now. Is this an oversight or is Dropbox no longer committed to this?

**Comment by tracker1** [comment]
@stephenreay It looks like the library is loaded on the site, it may be that it no longer shows instant feedback.

That said, in general you may be best off by simply suggesting what would be a good passphrase (don't use the term password) and possibly having a minimum length requirement alone.

In addition, you may want to do a server-side check against [haveibeenpwned.com range check](https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange).

For more general information: [see NIST.SP.800-63b](https://pages.nist.gov/800-63-3/sp800-63b.html), which does spell out complexity requirements as follows...

> Memorized secrets SHALL be **at least 8 characters in length** if chosen by the subscriber. Memorized secrets chosen randomly by the CSP or verifier SHALL be at least 6 characters in length and MAY be entirely numeric. If the CSP or verifier **disallows a chosen memorized secret based on its appearance on a blacklist of compromised values**, the subscriber SHALL be required to choose a different memorized secret. **No other complexity requirements for memorized secrets SHOULD be imposed.** A rationale for this is presented in Appendix A Strength of Memorized Secrets.

----

**Note:** currently working on an authentication management application, so have gone through this thoroughly.  Following are the options I plan to implement for internally managed accounts (also plans for 2FA and third party auth (Azure, AD, etc).  copied from my internal docs below...

## Default Passphrase Requirements

By default will match NIST.SP.800-63b Guidelines section 5.1.1 regarding memorized secrets.

* Normalization via NFKC
* Minimum of 8 characters
* Maximum of 64 characters

Hashing format will be the pbkdf2 (100000 rounds) (edit: replaced bcrypt with pbkdf2 (512bit length))

Configuration Options:

* Bad entry lockout (default: 3 attempts, max: 100, min: 1)
  * NIST Guideline: see 5.2.2
  * IP retry will match (in-memory only)
* Lockout Reset Minutes (default: 60 default)
  * 0 = disabled, means deactivated user reference
  * IP RESET 60 minutes when 0
* Minimum Length (default: 8)
  * NIST Guideline: "Verifiers SHALL require subscriber-chosen memorized secrets to be at least 8 characters in
length"
* Maximum Length (default: 64)
  * NIST Guideline: "Verifiers SHOULD permit subscriber-chosen memorized secrets at least 64 characters in
length"
* Password Expiration Days (default: 0/disabled)
  * NIST Guideline: "Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically). However, verifiers SHALL force a change if there is evidence of compromise of the authenticator."
* Must contain 3/4 [default] or 4/4 of these types of characters (2 options)
  * capital
  * lower-case
  * number
  * not a letter or number
  * NIST Guideline: "Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets"
* Beginning and trailing whitespace will be stripped
* ZXCVBN:
  * Options to force level:
    * Disabled [default]
    * Must meet zxcvbn level 3 (safely unguessable)
    * Must meet zccvbn level 4 (very unguessable)
  * Nist Guideline: Verifiers SHOULD offer guidance to the subscriber, such as a password-strength meter, visible even if unenforced
* Cannot be a known, compromized password (recommended)
  * Use safe/secure checking via [haveibeenpwned.com range check](https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange)
  * NIST Guideline: "When processing requests to establish and change memorized secrets, verifiers SHALL compare the prospective secrets against a list that contains values known to be commonly-used, expected, or compromised."
  * Configurable base URL for a matching API
    * Not provided but configurable via `RBI_PASSCHECK_URL` environment variable
    * Note: self-hosting will require a 12+ GB database (DynamoDB, Azure Table Storage and similar are a good match)

**Comment by stephenreay** [comment]
Hi @tracker1 

Given the topic of the site (low risk, a breach on a customer account can't really "harm" the customer), a lot of that advice is not 'sellable' as being practically helpful.

My main point here, was that Dropbox most definitely does not use this - I created a dummy account with "tester" as the password - the only reason it didn't accept "test" is it's less than 6 characters.

I'm just waiting for the next customer email complaining that "we're making it too hard" and using Dropbox as an example of a site with "easier" password "rules".

**Comment by lowe** [comment]
Hi @stephenreay -- from 2012-present, Dropbox has used the `zxcvbn` lib for feedback, but never for hard requirements. For example, on the [registration page](https://www.dropbox.com/register), look for the vertical strength meter to the right of the password input.
