### ISSUE TITLE
". . . . . ." is a good password

### ISSUE THREAD

**Issue by bukzor** [dropbox/zxcvbn#39]
It seems like the "repeat" strategy should apply to multiple-character runs.

**Comment by BoiteAWeb** [comment]
```javascript
  ²  ²
```
is also a 6 chars "strong" password.

**Comment by tracker1** [comment]
@BoiteAWeb makes me think that maybe a trim should be done before checking.. (I tend to trim any password inputs in case of extra characters with copy/paste.

**Comment by BoiteAWeb** [comment]
nono, never trim a password, i can decide to start my password with a space, this is not forbidden.

**Comment by tracker1** [comment]
@BoiteAWeb given how many times copy/paste includes extra leading/trailing whitespace and the resulting error, and confusion... it's probably better to not allow it... maybe not in this tool, but in practice... imho.

**Comment by stramel** [comment]
I agree with @BoiteAWeb.

**Comment by lowe** [comment]
as of 3.5.0, '. . . . . .' is no longer a good password! the new implementation of `repeat_match` catches multi-character repeat sequences.
