### ISSUE TITLE
Has 'time to crack' gotten shorter with more GPUs?

### ISSUE THREAD

**Issue by VWFeature** [dropbox/zxcvbn#52]
The Ars Technica article 
http://arstechnica.com/security/2013/05/how-crackers-make-minced-meat-out-of-your-passwords/2/ 
said that they quickly bruteforced all passwords of 6 or less, plus the all-upper or all-lower passwords of length 7 or 8 in just 41 seconds.  
Yet the 'crack time (display):' for an all caps 7 char password is 5 years. I suspect more GPU power has made cracking faster.

**Comment by lowe** [comment]
Closing this out for now, but it's on my roadmap to remove password storage assumptions + cracking hardware assumptions from zxcvbn scoring, such that a hardware-independent guessability estimate is emitted instead. See #58 for more discussion.
