### ISSUE TITLE
Crack time is too optimistic

### ISSUE THREAD

**Issue by kimmobrunfeldt** [dropbox/zxcvbn#58]
zxcvbn assumes that passwords are hashed with bcrypt, scrypt or PBKDF2. This is fine when you know exactly what hashing algorithm is used. Sadly this isn't always the case and it should be stated more clearly in the project documentation.

The assumed time per guess(with strong hash) is **1/10 seconds** and with 100 cores that makes **1/10000 seconds**. With MD5, SHA256 or SHA512, the situation is different. For example with Oclhashcat, it takes just **1/1952000000 seconds** to calculate single SHA512 hash(using 8 GPUs). See [oclHashcat performance table](http://hashcat.net/oclhashcat/#performance).

For example with `skjiqonjhrp`, zxcvbn returns 3 years as crack time. If it was hashed with SHA512, the crack time would be about **320 seconds**. I calculated it with entropy returned by zxcvbn and using the same formula as in your blog post: `0.5 * 2^40.188 * 1/1952000000`. The difference is **huge**.

If people would use this as a general "how good is my password" meter, it would give overly optimistic results since there are countless of services out there using MD5/SHA256/SHA512.

**Comment by spiderwick** [comment]
spare yourself you***

**Comment by lowe** [comment]
I made the choice of a slow hash constant with the assumption that any developer that cares enough to use zxcvbn for their signup flow would also likely be properly hashing. I'm now realizing that isn't a perfect assumption -- it means it's harder to use zxcvbn for standalone "how strong is my password" tools for example, in which case you'd want to err on the side of fast hashing. I'm not sure it's worth making this more configurable though -- what about other scenarios, like, sites that don't salt, sites that store in plaintext, etc? It's hard to define a universal measure when many sites out there store passwords insecurely.

**Comment by lowe** [comment]
Closing this issue for now, but it's on my roadmap to reconfigure zxcvbn scores to return a hardware-independent "guessability" estimate instead of crack time estimate, so that less assumptions are made about hashing schemes and cracker capabilities.
