### ISSUE TITLE
QML support

### ISSUE THREAD

**Issue by cinemast** [dropbox/zxcvbn#63]
Can this also be used in Qt's QML as an JavaScript import module? I cannot get it to work.

**Comment by lowe** [comment]
Hi @cinemast, I know it's been a while, but this should work now (assuming QML plays nicely with CommonJS or AMD modules)

**Comment by cinemast** [comment]
Could you provide a quick example? Thank you for fixing this :)

**Comment by lowe** [comment]
Hrm, I hadn't used QML before and didn't realize it uses its own module standard. I thought it played nicely with node packages. 

This might not be easy to do after all...the closest I could find is this incomplete node compatibility layer for QMT. 

https://github.com/trollixx/node.qml
