### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by flatr0ze** [dropbox/zxcvbn#64]
Happens when one of my variables in the array of the second argument is of type "undefined".

I used `[variable || '']` in my code but it just feels like it's something that should be implemented within the core of zxcvbn, otherwise it just won't work whenever one of the members of the `user_inputs` array is not a string.

Thants.

**Comment by lowe** [comment]
this should now work the way you suggest, thanks
