### ISSUE TITLE
having trouble installing

### ISSUE THREAD

**Issue by crittelmeyer** [dropbox/zxcvbn#71]
Hi, I'm trying to install zxcvbn by adding it to my project's bower.json, but it seems unable to find the module. If I install it directly using "bower install", it works as expected. Should it be trying to pull from lowe/zxcvbn? I see that navigating to github.com/lowe/zxcvbn in my browser redirects me here. Perhaps that is confusing bower somehow? For now I have it working by using https://raw.githubusercontent.com/dropbox/zxcvbn/482ed03a10779ec125100721c2d828b97abf9ea6/zxcvbn.js for my url, but obviously this is not ideal. Any ideas?

**Comment by BridgeAR** [comment]
Seems like you have to use "zxcvbn": "v1.0" ... Please fix this so it's working with normal version numbers

**Comment by BridgeAR** [comment]
bower zxcvbn#v1.0                  invalid-meta zxcvbn is missing "main" entry in bower.json
bower zxcvbn#v1.0                  invalid-meta zxcvbn is missing "ignore" entry in bower.json

**Comment by lowe** [comment]
Hi @crittelmeyer and @BridgeAR, I just fixed the bower registry to point to dropbox/zxcvbn (lowe/zxcvbn was the former home), started using standard x.y.z semver tagging, fixed a few bower setup bugs, and added bower setup instructions to the README. 

It should just work now, thanks for reporting and let me know if you still run into issues!
