### ISSUE TITLE
Test.js help 

### ISSUE THREAD

**Issue by Cr1T1cal** [dropbox/zxcvbn#84]
Hey im having a few difficulties with the test.js im trying to remove the test_passwords and #results Id 
and only keep the #search-passwords so basicaly i want to just show the the password tryped no examples 
and one more little bug iv encountered is that iv added a scoller div to the match sequence but it only seems to work on the test_passwords 

here my code;
<pre><code>
var props_tmpl, results_tmpl, test_passwords, zxcvbn_load_hook;

test_passwords = 'n0Ts0Cr4ck4bL3';
results_tmpl = '{{#results}}\n<div class="portlet gren">\n<div class="portlet-title">\n<div class="caption">\n	<i class="fa fa-key"></i>Password Statistics\n</div>\n<div class="tools">\n<a href="javascript:;" class="collapse"></a>\n<a href="javascript:;" class="reload"></a>\n<a href="" class="fullscreen"></a>\n<a href="javascript:;" class="remove"></a>\n</div>\n</div>\n<div class="portlet-body">\n<table class="result">\n  <tr>\n    <td>password: </td>\n    <td><strong>{{password}}</strong></td>\n  </tr>\n  <tr>\n    <td>entropy: </td>\n    <td>{{entropy}}</td>\n  </tr>\n  <tr>\n    <td>composition: </td>\n    <td>{{composition}}</td>\n  </tr>\n  <tr>\n    <td><strong>acceptable:</strong> </td>\n    <td><strong>{{acceptable}}</strong></td>\n  </tr>\n  <tr>\n    <td>crack time (seconds): </td>\n    <td>{{crack_time}}</td>\n  </tr>\n  <tr>\n    <td>crack time (display): </td>\n    <td>{{crack_time_display}}</td>\n  </tr>\n  <tr>\n    <td>score from 0 to 4:</td>\n    <td>{{score}}</td>\n  </tr>\n  <tr>\n    <td>calculation time (ms): </td>\n    <td>{{calc_time}}</td>\n  </tr>\n  <tr>\n </tr>\n</table>\n</div>\n{{& match_sequence_display}}\n{{/results}}';
props_tmpl = '<td colspan="2"><strong>match sequence:</strong></td>\n<div class="portlet-body">\n<div class="scroller" style="height:250px">\n{{& match_sequence_display}}\n<div class="match-sequence">\n{{#match_sequence}}\n<table>\n  <tr>\n    <td colspan="2">\'{{token}}\'</td>\n  </tr>\n  <tr>\n    <td>pattern:</td>\n    <td>{{pattern}}</td>\n  </tr>\n  <tr>\n    <td>entropy:</td>\n    <td>{{entropy}}</td>\n  </tr>\n  {{#cardinality}}\n  <tr>\n    <td>cardinality:</td>\n    <td>{{cardinality}}</td>\n  </tr>\n  {{/cardinality}}\n  {{#rank}}\n  <tr>\n    <td>dict-name:</td>\n    <td>{{dictionary_name}}</td>\n  </tr>\n  <tr>\n    <td>rank:</td>\n    <td>{{rank}}</td>\n  </tr>\n  <tr>\n    <td>base-entropy:</td>\n    <td>{{base_entropy}}</td>\n  </tr>\n  <tr>\n    <td>upper-entropy:</td>\n    <td>{{uppercase_entropy}}</td>\n  </tr>\n  {{/rank}}\n  {{#l33t}}\n  <tr>\n    <td>l33t-entropy:</td>\n    <td>{{l33t_entropy}}</td>\n  </tr>\n  <tr>\n    <td>l33t subs:</td>\n    <td>{{sub_display}}</td>\n  </tr>\n  <tr>\n    <td>un-l33ted:</td>\n    <td>{{matched_word}}</td>\n  </tr>\n  {{/l33t}}\n  {{#graph}}\n  <tr>\n    <td>graph: </td>\n    <td>{{graph}}</td>\n  </tr>\n  <tr>\n    <td>turns: </td>\n    <td>{{turns}}</td>\n  </tr>\n  <tr>\n    <td>shifted keys: </td>\n    <td>{{shifted_count}}</td>\n  </tr>\n  {{/graph}}\n  {{#repeated_char}}\n  <tr>\n    <td>repeat-char:</td>\n    <td>\'{{repeated_char}}\'</td>\n  </tr>\n  {{/repeated_char}}\n  {{#sequence_name}}\n  <tr>\n    <td>sequence-name:</td>\n    <td>{{sequence_name}}</td>\n  </tr>\n  <tr>\n    <td>sequence-size</td>\n    <td>{{sequence_space}}</td>\n  </tr>\n  <tr>\n    <td>ascending:</td>\n    <td>{{ascending}}</td>\n  </tr>\n  {{/sequence_name}}\n  {{#day}}\n  <tr>\n    <td>day:</td>\n    <td>{{day}}</td>\n  </tr>\n  <tr>\n    <td>month:</td>\n    <td>{{month}}</td>\n  </tr>\n  <tr>\n    <td>year:</td>\n    <td>{{year}}</td>\n  </tr>\n  <tr>\n    <td>separator:</td>\n    <td>\'{{separator}}\'</td>\n  </tr>\n  {{/day}}\n</table>\n{{/match_sequence}}\n</div></div></div>';
zxcvbn_load_hook = function() {
  return $(function() {
    var last_q, password, r, rendered, results_lst, _i, _len, _listener, _ref;
    results_lst = [];
    _ref = test_passwords.split('\n');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      password = _ref[_i];
      if (!(password)) continue;
      r = zxcvbn(password);

      comp_result = cyg_test_composition(password, 'Password');
      r.composition = comp_result["message"];
      if (comp_result["valid"] && r.entropy >= 40) {
        r.acceptable = 'yes';
      } else {
        r.acceptable = 'no';
      }

      r.match_sequence_display = Mustache.render(props_tmpl, r);
      results_lst.push(r);
    }
    rendered = Mustache.render(results_tmpl, {
      results: results_lst
    });
    $('#results').html(rendered);
    last_q = '';
    _listener = function() {
      var current, results;
      current = $('#register_password').val();
      if (!current) {
        $('#search-results').html('');
        return;
      }
      if (current !== last_q) {
        last_q = current;
        r = zxcvbn(current);

        comp_result = cyg_test_composition(current, 'Password');
        r.composition = comp_result["message"];
        if (comp_result["valid"] && r.entropy >= 40) {
          r.acceptable = 'yes';
        } else {
          r.acceptable = 'no';
        }

        r.match_sequence_display = Mustache.render(props_tmpl, r);
        results = {
          results: [r]
        };
        rendered = Mustache.render(results_tmpl, results);
        return $('#search-results').html(rendered);
      }
    };
    return setInterval(_listener, 100);
  });
};
</code></pre>
PS sorry didnt know how to stop 
results_tmpl =
and 
props_tmpl = 
from going weird but there no actually like that

I would appreciate any help as my js iisnt that good

**Comment by lowe** [comment]
Hi @Cr1T1cal , I think this will do what you want. 

In demo/demo.coffee, delete these lines: 

``` coffeescript
    rendered = Mustache.render(results_tmpl, {
      results: results_lst,
    })
    $('#results').html(rendered)
```

In demo/index.html, remove these lines:

``` html
<div id="examples-container">
<h1 id="examples">examples</h1>
<div id="results">
</div>
```

From the command line run,

``` shell
cd zxcvbn/demo
coffee -c demo.coffee
```

then load demo/index.html in your browser.
