### ISSUE TITLE
console.log('hi')

### ISSUE THREAD

**Issue by binarykitchen** [dropbox/zxcvbn#85]
seeing that in your latest v2.0 heh

**Comment by lowe** [comment]
Embarrassing :\ thanks or catching.

Fixed and retagged to 2.0.1. I tried to remove the console.log() only and retag as 2.0.0, but npm doesn't allow this (for good reason, in retrospect). So...2.0.0 is gone. 

Next time around I won't try to change a version in-place, which I already knew wasn't a great idea.

**Comment by binarykitchen** [comment]
yeah, shit happens

**Comment by lowe** [comment]
:)
