### ISSUE TITLE
bower broken with non-default directory

### ISSUE THREAD

**Issue by tomsommer** [dropbox/zxcvbn#86]
```var ZXCVBN_SRC = 'bower_components/zxcvbn/zxcvbn.js';```

"bower_components" is not a static path, it could be called anything (mine is called /assets/), see http://bower.io/docs/config/#directory

**Comment by MacMadame** [comment]
Not only is bower_components not always the directory where the files are located, but if you package your javascript into one minified file for a production environment, then the async loading code doesn't work at all. What does work is to edit the bower.json file so it's only loading in the zxcvbn.js file. 

I don't actually think it's necessary to load the code in this way. The zxcvbn.js file isn't that big compared to many common plug-ins, so you are adding complexity without much benefit.

**Comment by tomsommer** [comment]
True. using a <script> tag with zxcvbn.js and the "defer" attribute works just as well.

**Comment by lowe** [comment]
Hi @tomsommer and @MacMadame,

I took your feedback to heart and worked this into the latest release. bower setup now works how you'd expect, and the async loader scripts no longer exist in the repo (put them as a suggestion in the README instead). See the 3.0.0 release to learn more.
