### ISSUE TITLE
Issues with Passwords saying they're strong when comparing them to others that arent.

### ISSUE THREAD

**Issue by kingfishercreative** [dropbox/zxcvbn#89]
Hi,

I'm not sure if this is an issue or just interesting. However if a password is: aAaAaAaAaAaAaAaAaAaAa it's considered strong where as abC12!23456789123456 isn't strong. Can you confirm that this is working correctly to display that the first password is stronger than the second?

**Comment by bmurray** [comment]
I submitted a pull request #65 that addresses this problem. It probably needs to be updated for the current release tho.

**Comment by lowe** [comment]
thanks for posting, this is one of the biggest problems with zxcvbn (lack of multi-character repeat detection) and a fix is coming soon after i finish unit tests + code coverage.) will keep open until it's fixed.

**Comment by lowe** [comment]
This is fixed in 3.5.0 -- 'aAaAaA' is recognized as a multi-character repeat string.  See the new impl of `repeat_match` to see how it works.
