### ISSUE TITLE
Reversed word check

### ISSUE THREAD

**Issue by Shyiy** [dropbox/zxcvbn#94]
While checking for password substring presence in the various wordlists it would be best to also check for the reversed string, which could then trigger a match (but a slightly better score compared to the "normal" variant).

**Comment by jalcine** [comment]
Assuming that there isn't already words that are reversed (like palindromes) in dictionary; wouldn't this duplicate the run time of the check?

**Comment by lowe** [comment]
added in version 3.5.0! 

this does duplicate the run time of dictionary matching, however it isn't a bottleneck so no worries!
