### ISSUE TITLE
sequence_entropy is tested using a dummy test

### ISSUE THREAD

**Issue by alextekartik** [dropbox/zxcvbn#95]
in test-scoring.coffee, test "sequence entropy", the test compares 2 exact same calls

    t.equal scoring.sequence_entropy(match), scoring.sequence_entropy(match), msg

although it should test the result against the value in the array

    t.equal scoring.sequence_entropy(match), entropy, msg

To note that this test is failing then

**Comment by lowe** [comment]
Thanks for catching, pushed a fix!
