### ISSUE TITLE
Unexpected result returned by call to zxcvbn function. 

### ISSUE THREAD

**Issue by danr1979** [dropbox/zxcvbn#99]
Hi.

When I call `zxcvbn('Tr0ub4dour&3')` from my Javascript code the returned value is not the object described in the "Usage" section of the main GitHub page, i.e.:

    result.entropy            # bits

    result.crack_time         # estimation of actual crack time, in seconds.

    result.crack_time_display # same crack time, as a friendlier string:
                              # "instant", "6 minutes", "centuries", etc.

    result.score              # [0,1,2,3,4] if crack time is less than
                              # [10**2, 10**4, 10**6, 10**8, Infinity].
                              # (useful for implementing a strength bar.)

    result.match_sequence     # the list of patterns that zxcvbn based the
                              # entropy calculation on.

    result.calc_time          # how long it took zxcvbn to calculate an answer,
                              # in milliseconds.

but instead is the following object:

    calc_time: 3
    guesses: 594963824
    guesses_log10: 8.7744905598213
    password: "Tr0ub4dour&3"
    sequence: Array[2]
    sequence_length_multiplier_log10: 0.30102999566398114
    sequence_product_log10: 8.473460564157321

I cannot seem to get the correct return value.

Any help would be appreciated.

Many thanks.

**Comment by lowe** [comment]
Hi @danr1979, sorry for the confusion. I'm making some changes to the API and haven't updated the documentation yet. Switching to the latest tagged release will fix your problem -- results will match the docs. 

See this thread: 
https://github.com/dropbox/zxcvbn/issues/98

I'll keep your issue open until the docs are fixed.

**Comment by dpogue** [comment]
We're seeing this issue with the version published to npm (3.5.0)

**Comment by lowe** [comment]
are you sure? i just tried. 

```
% mkdir testdir
% cd testdir
% npm install zxcvbn
zxcvbn@3.5.0 node_modules/zxcvbn
% node
> zxcvbn = require('zxcvbn')
> zxcvbn('asdf')
{ password: 'asdf',
  entropy: 7.435,
  match_sequence:
   [ { pattern: 'dictionary',
       i: 0,
       j: 3,
       token: 'asdf',
       matched_word: 'asdf',
       rank: 173,
       dictionary_name: 'passwords',
       reversed: false,
       base_entropy: 7.4346282276367255,
       uppercase_entropy: 0,
       reversed_entropy: 0,
       l33t_entropy: 0,
       entropy: 7.4346282276367255 } ],
  crack_time: 0.009,
  crack_time_display: '0.008650000000000007 seconds',
  score: 0,
  calc_time: 9 }
```

**Comment by dpogue** [comment]
Oops, yeah, it works from npm. Had a cached git version in my node_modules.

**Comment by danr1979** [comment]
Thanks for your help.

**Comment by lowe** [comment]
OK @danr1979 , docs should now be good to go (with a much improved interface from earlier versions)! Let me know if anything doesn't make sense.

**Comment by danr1979** [comment]
Cool. Thanks for the update.
